BookStore/Models/Stores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookStore.Models
{
    public class Stores
    {
        public int storeId { get; set; }

        [StringLength(30, MinimumLength = 1)]
        [Required]
        public string name { get; set; }

        [StringLength(100, MinimumLength = 5)]
        [Required]
        public string address { get; set; }

        [Required]
        public int phone { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required]
        public string email { get; set; }

        [StringLength(20, MinimumLength = 11)]
        [Required]
        public string openingTime { get; set; }
    }
}

BookStore/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStore.DAL;
using BookStore.Models;


namespace BookStore.Controllers
{
    public class StoresController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Stores
        public ActionResult Index(string searchString , string storeHours)
        {
            /************* Create List Of Opening Hours ****************/
            var hoursList = new List<string>();
            var hoursQry = from d in db.bookStores
                           orderby d.openingTime
                           select d.openingTime;
            hoursList.AddRange(hoursQry.Distinct());
            ViewBag.storeHours = new SelectList(hoursList);

            var stores = from b in db.bookStores
                        select b;

            if (!String.IsNullOrEmpty(searchString)) //Searching By Address
            {
                stores = stores.Where(s => s.address.Contains(searchString) );
            }

            if (!string.IsNullOrEmpty(storeHours)) //Searching By Opening Hours
            {
                stores = stores.Where(x => x.openingTime.Contains(storeHours));
            }

            return View(stores);
        }

        // GET: Stores/Details/5
        public ActionResult Details(int? id)
        {

           if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stores stores = db.bookStores.Find(id);
            if (stores == null)
            {
                return HttpNotFound();
            }
            return View(stores);
        }

        // GET: Stores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StoresId,Name,Address,Phone,Email,OpeningTime")] Stores stores)
        {
            if (ModelState.IsValid)
            {
                db.bookStores.Add(stores);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(stores);
        }

        // GET: Stores/Edit/5
        [Authorize(Users = "Admin@gmail.com")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stores stores = db.bookStores.Find(id);
            if (stores == null)
            {
                return HttpNotFound();
            }
            return View(stores);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Admin@gmail.com")]
        public ActionResult Edit([Bind(Include = "StoresId,Name,Address,Phone,Email,OpeningTime")] Stores stores)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stores).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stores);
        }

        // GET: Stores/Delete/5
        [Authorize(Users = "Admin@gmail.com")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stores stores = db.bookStores.Find(id);
            if (stores == null)
            {
                return HttpNotFound();
            }
            return View(stores);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stores stores = db.bookStores.Find(id);
            db.bookStores.Remove(stores);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookStore/Views/Stores/Create.cshtml
@model BookStore.Models.Stores

@Styles.Render("~/Content/style.css")
@Scripts.Render("~/bundles/modernizr")
<div id="addTitle">
    Add-Store
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Raw("Opening Time - (Ex. 08:00 - 17:00)")
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpeningTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpeningTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="editBack">
    @Html.ActionLink("Back to Stores", "Index")
</div>

BookStore/Views/Stores/Delete.cshtml
@model BookStore.Models.Stores

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpeningTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpeningTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookStore/Views/Stores/Details.cshtml
@model BookStore.Models.Stores
@Styles.Render("~/Content/style.css")
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true&amp;language=en"></script>
<script type="text/javascript" src="~/Scripts/gmap3.js"></script>
<script type="text/javascript">
    $(function () {

        $("#test").gmap3({
            infowindow: {
                address: "@Html.DisplayFor(model => model.Address)",
                options: {
                    content: "@Html.DisplayFor(model => model.Name) / @Html.DisplayFor(model => model.Address)",
                },
                callback: function () {
                    $(this).gmap3('get').setZoom(17);
                }
            }
        })
    })
</script>

<h2>@Html.DisplayFor(model => model.Name)</h2>
<table id="main" style="width:100%">
    <tr>
        <td><b>Address: </b>@Html.DisplayFor(model => model.Address) /<b> Opening Time: </b>@Html.DisplayFor(model => model.OpeningTime)</td>
    </tr>
    <tr>
        <td><b>Phone Number: </b>@Html.Raw("+972 ") @Html.DisplayFor(model => model.Phone) /<b> Email: </b> @Html.DisplayFor(model => model.Email)</td>
    </tr>
    <tr>
        <td><div id="test" class="gmap3"></div></td>
    </tr>
    <tr>
         <td><center><b><br /></b></center></td>
</tr>
</table>
<div class="back"><center>@Html.ActionLink("Back to Stores", "Index")</center></div>

BookStore/Views/Stores/Edit.cshtml
@model BookStore.Models.Stores
<div id="addTitle">
    Edit Store
</div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.StoresId)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OpeningTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OpeningTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OpeningTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
            <div class="deleteEdit">
                @Html.ActionLink("Delete", "Delete", new { id = Model.StoresId })
            </div>
        </div>

    }

    <div class="editBack">
     @Html.ActionLink("Back to Stores", "Index")
    </div>


BookStore/Views/Stores/Index.cshtml
@model IEnumerable<BookStore.Models.Stores>
@Styles.Render("~/Content/style.css")
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true&amp;language=en"></script>
<script type="text/javascript" src="~/Scripts/gmap3.js"></script>
<div class="listTitle">Stores</div>

<p>
<center><div class="commentList">
@if (User.Identity.IsAuthenticated)
   {
        @Html.ActionLink("Add Store", "Create")
   }
</div></center>
</p>
<center>
@using (Html.BeginForm("Index", "Stores", FormMethod.Get))
{
    <p>    
        Address: @Html.TextBox("searchString")<br />
        Opening Hours: @Html.DropDownList("storeHours", "All") <input type="submit" value="Search" />
    </p>
}   
    </center>
@foreach (var item in Model)
{
    <script type="text/javascript">
    $(function () {

        $("#test").gmap3({
            marker: {
                address: "@Html.DisplayFor(modelItem => item.Address)",
                events: { // events trigged by markers
                    click: function () {
                        alert("@Html.DisplayFor(modelItem => item.Name) / @Html.DisplayFor(modelItem => item.Address)");
                    }
                },
                callback: function () {
                    $(this).gmap3('get').setZoom(09);
                }
            }
        })
    })
</script>
    <br />
    <table id="bookList" style="width:100%">
        <tr>
            <td class="title">@Html.DisplayFor(modelItem => item.Name)</td>
            <td class="content"><u>Address</u>: @Html.DisplayFor(modelItem => item.Address) </td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td class="content"><u>Opening Time</u>: @Html.DisplayFor(modelItem => item.OpeningTime)</td>
            <td class="detailsList">
                <center>
                    @Html.ActionLink("Details", "Details", new { id = item.StoresId }) @if (User.Identity.Name.Equals("Admin@gmail.com"))
                    {@Html.Raw(" / ") @Html.ActionLink("Edit", "Edit", new { id = item.StoresId })}
                </center>
            </td>
        </tr>
        <tr>
            <td></td>
            <td class="content"><u>Email</u>: @Html.DisplayFor(modelItem => item.Email)</td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td><u>Phone</u>: @Html.Raw("+972 ")@Html.DisplayFor(modelItem => item.Phone)</td>
        </tr>
    </table>

}

<table id="main1" style="width:100%">
    <tr>
        <td class="map"><center><div id="test" class="gmap3"></div></center></td>
    </tr>
</table>
    