BookStore/Models/List.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class List
    {
        public int listID { get; set; }

        [StringLength(30,MinimumLength = 5)]
        [Required]
        public string title { get; set; }

        [StringLength(1000, MinimumLength = 5)]
        [Required]
        public string content { get; set; }

        [StringLength(20, MinimumLength = 3)]
        [Required]
        public string author { get; set; }

        [StringLength(30, MinimumLength = 3)]
        [Required]
        public string publisher { get; set; }

        [Required]
        public string genre { get; set; }

        [DataType(DataType.Currency)]
        [Required]
        public double price { get; set; }

        [Range(1900,2015)]
        [Required]
        public int year { get; set; }

        [DataType(DataType.ImageUrl)]
        [Required]
        public string picture { get; set; }

        public double rating { get; set; }

        public virtual ICollection<Comments> comments { get; set; }
    }
}

BookStore/ViewModels/ListViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using BookStore.Models;
namespace BookStore.ViewModels
{
    public class ListViewModels
    {
        public string genre { get; set; }
        public int countBook { get; set; }
    }
}

BookStore/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStore.DAL;
using BookStore.Models;

namespace BookStore.Controllers
{
    public class ListController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: List
        public ActionResult Index(string sortOrder)
        {
            var sortList = from s in db.bookList
                            select s;
            /********************************************
                 Order Books BY Year or Book Name or Price
            *********************************************/
            ViewBag.BookSortParm = String.IsNullOrEmpty(sortOrder) ? "book_desc" : "";
            ViewBag.YearSortParm = sortOrder == "year" ? "year_desc" : "year";
            ViewBag.PriceSortParm = sortOrder == "price" ? "price_desc" : "price";

            switch (sortOrder)
            {
                case "book_desc":
                    sortList = sortList.OrderByDescending(s => s.title);
                    break;
                case "year_desc":
                    sortList = sortList.OrderByDescending(s => s.year);
                    break;
                case "year":
                    sortList = sortList.OrderBy(s => s.year);
                    break;
                case "price_desc":
                    sortList = sortList.OrderByDescending(s => s.price);
                    break;
                case "price":
                    sortList = sortList.OrderBy(s => s.price);
                    break;
                default:
                    sortList = sortList.OrderBy(s => s.listID);
                    break;
            }
            return View(sortList.ToList());
        }
        public ActionResult Search(string searchString, string bookGenre, string bookAuthor, int? bookYear, double? bookPrice)
        {
            /************* Create List Of Years ****************/
            var YearList = new List<int>();
            var YearQry = from a in db.bookList
                          orderby a.year
                          select a.year;
            YearList.AddRange(YearQry.Distinct());
            ViewBag.bookYear = new SelectList(YearList);

            /************* Create List Of Genres ****************/
            var GenreList = new List<string>();
            var GenreQry = from d in db.bookList
                           orderby d.genre
                           select d.genre;
            GenreList.AddRange(GenreQry.Distinct());
            ViewBag.bookGenre = new SelectList(GenreList);

            var books = from b in db.bookList
                        select b;

            if (!String.IsNullOrEmpty(searchString)) //Searching By Title
            {
                books = books.Where(s => s.title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(bookGenre)) //Searching By Genre
            {
                books = books.Where(x => x.genre == bookGenre);
            }

            if (!string.IsNullOrEmpty(bookAuthor)) //Searching By Author
            {
                books = books.Where(y => y.author.Contains(bookAuthor));
            }

            if (bookYear > 0) //Searching By Year
            {
                books = books.Where(z => z.year == bookYear);
            }
            if (bookPrice > 0) //Searching By Price
            {
                books = books.Where(z => z.price >= bookPrice);
            }
            return View(books);
        }
        // GET: Search
        public ActionResult SearchBook(string searchString, string bookGenre, string bookAuthor, int? bookYear, double? bookPrice)
        {
            /************* Create List Of Years ****************/
            var YearList = new List<int>();
            var YearQry = from a in db.bookList
                          orderby a.year
                          select a.year;
            YearList.AddRange(YearQry.Distinct());
            ViewBag.bookYear = new SelectList(YearList);

            /************* Create List Of Genres ****************/
            var GenreList = new List<string>();
            var GenreQry = from d in db.bookList
                           orderby d.genre
                           select d.genre;
            GenreList.AddRange(GenreQry.Distinct());
            ViewBag.bookGenre = new SelectList(GenreList);

            var books = from b in db.bookList
                        select b;

            if (!String.IsNullOrEmpty(searchString)) //Searching By Title
            {
                books = books.Where(s => s.title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(bookGenre)) //Searching By Genre
            {
                books = books.Where(x => x.genre == bookGenre);
            }

            if (!string.IsNullOrEmpty(bookAuthor)) //Searching By Author
            {
                books = books.Where(y => y.author.Contains(bookAuthor));
            }

            if (bookYear > 0) //Searching By Year
            {
                books = books.Where(z => z.year == bookYear);
            }
            if (bookPrice > 0) //Searching By Price
            {
                books = books.Where(z => z.price >= bookPrice);
            }
            return View(books);
        }


        public ActionResult BookStatistics()
        {
            var books = from d in db.bookList
                        select d;
            /*************************
                Genre Statistics
            *************************/
            var g = books.Where(z => z.genre.Contains("Kids"));
            int gK = g.Count();
            ViewBag.gK = gK;

            g = books.Where(z => z.genre.Contains("Sport"));
            int gS = g.Count();
            ViewBag.gS = gS;

            g = books.Where(z => z.genre.Contains("Biography"));
            int gB = g.Count();
            ViewBag.gB = gB;

            g = books.Where(z => z.genre.Contains("Romantic"));
            int gR = g.Count();
            ViewBag.gR = gR;

            g = books.Where(z => z.genre.Contains("Action"));
            int gA = g.Count();
            ViewBag.gA = gA;

            g = books.Where(z => z.genre.Contains("History"));
            int gHi = g.Count();
            ViewBag.gHi = gHi;

            g = books.Where(z => z.genre.Contains("Classics"));
            int gC = g.Count();
            ViewBag.gC = gC;

            g = books.Where(z => z.genre.Contains("Drama"));
            int gD = g.Count();
            ViewBag.gD = gD;

            /*************************
                Years Statistics
            *************************/
            g = books.Where(z => z.year > 1900 && z.year < 1920);
            int g1 = g.Count();
            ViewBag.g1 = g1;

            g = books.Where(z => z.year > 1921 && z.year < 1940);
            int g2 = g.Count();
            ViewBag.g2 = g2;

            g = books.Where(z => z.year > 1941 && z.year < 1960);
            int g3 = g.Count();
            ViewBag.g3 = g3;

            g = books.Where(z => z.year > 1961 && z.year < 1980);
            int g4 = g.Count();
            ViewBag.g4 = g4;

            g = books.Where(z => z.year > 1981 && z.year < 2000);
            int g5 = g.Count();
            ViewBag.g5 = g5;

            g = books.Where(z => z.year > 2001 && z.year < 2015);
            int g6 = g.Count();
            ViewBag.g6 = g6;
            
            return View();
        }
        // GET: List/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List list = db.bookList.Find(id);
            CalcRatAvg(id);

            if (list == null)
            {
                return HttpNotFound();
            }
            return View(list);
        }

        // GET: List/CommentDetails/5
        public ActionResult CommentDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = db.bookComments.Find(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // GET: List/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: List/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ListID,Title,Content,Author,Publisher,Genre,Price,Year,Picture,Rating")] List list)
        {
            if (ModelState.IsValid)
            {
                db.bookList.Add(list);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(list);
        }

        // GET: List/Edit/5
        [Authorize(Users = "Admin@gmail.com")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List list = db.bookList.Find(id);
            if (list == null)
            {
                return HttpNotFound();
            }
            return View(list);
        }

        // POST: List/Edit/5

BookStore/Views/List/BookStatistics.cshtml
@model BookStore.Models.List
@Styles.Render("~/Content/style.css")
@Scripts.Render("~/bundles/modernizr")
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>

<head>
    <title></title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>

<body>
    <center><h3><b>Books By Years:</b></h3></center>

    <div id="canvas-holder2">
        <canvas id="chart2" width="100" height="100" />
    </div>


    <center><h3><b>Genres:</b></h3></center>
    <div id="canvas-holder">
        <canvas id="chart-area2" width="400" height="400" />
    </div>
    <div id="chartjs-tooltip"></div>

    <script>
    Chart.defaults.global.customTooltips = function (tooltip) {
        // Tooltip Element
        var tooltipEl = $('#chartjs-tooltip');
        // Hide if no tooltip
        if (!tooltip) {
            tooltipEl.css({
                opacity: 0
            });
            return;
        }
        // Set caret Position
        tooltipEl.removeClass('above below');
        tooltipEl.addClass(tooltip.yAlign);
        // Set Text
        tooltipEl.html(tooltip.text);
        // Find Y Location on page
        var top;
        if (tooltip.yAlign == 'above') {
            top = tooltip.y - tooltip.caretHeight - tooltip.caretPadding;
        } else {
            top = tooltip.y + tooltip.caretHeight + tooltip.caretPadding;
        }
        // Display, position, and set styles for font
        tooltipEl.css({
            opacity: 1,
            left: tooltip.chart.canvas.offsetLeft + tooltip.x + 'px',
            top: tooltip.chart.canvas.offsetTop + top + 'px',
            fontFamily: tooltip.fontFamily,
            fontSize: tooltip.fontSize,
            fontStyle: tooltip.fontStyle,
        });
    };
    var pieData = [{
        value: @ViewBag.gK ,
        color: "#000066",
        highlight: "#333385",
        label: "Kids"
    }, {
        value: @ViewBag.gS,
        color: "#0000FF",
        highlight: "#3333FF",
        label: "Sport"
    }, {
        value: @ViewBag.gB,
        color: "#00A6CF",
        highlight: "#33B8D9",
        label: "Biography"
    }, {
        value: @ViewBag.gR,
        color: "#2EB82E",
        highlight: "#58C658",
        label: "Romantic"
    }, {
        value: @ViewBag.gA,
        color: "#FFFF00",
        highlight: "#FFFF33",
        label: "Action"
    },  {
        value: @ViewBag.gHi,
            color: "#FF0000",
            highlight: "#FF3333",
            label: "History"
        },
        {
            value: @ViewBag.gC,
            color: "#003300",
            highlight: "#4D704D",
            label: "Classics"
        },
        {
            value: @ViewBag.gD,
            color: "#4700B2",
            highlight: "#6C33C1",
            label: "Drama"
        }];

        var ctx2 = document.getElementById("chart-area2").getContext("2d");
        window.myPie = new Chart(ctx2).Pie(pieData);
    </script>


    <!------------- LINE CHART   ---------------->


    <script>
        Chart.defaults.global.pointHitDetectionRadius = 1;
        Chart.defaults.global.customTooltips = function(tooltip) {
            var tooltipEl = $('#chartjs-tooltip');
            if (!tooltip) {
                tooltipEl.css({
                    opacity: 0
                });
                return;
            }
            tooltipEl.removeClass('above below');
            tooltipEl.addClass(tooltip.yAlign);
            var innerHtml = '';
            for (var i = tooltip.labels.length - 1; i >= 0; i--) {
                innerHtml += [
                    '<div class="chartjs-tooltip-section">',
                    '	<span class="chartjs-tooltip-key" style="background-color:' + tooltip.legendColors[i].fill + '"></span>',
                    '	<span class="chartjs-tooltip-value">' + tooltip.labels[i] + '</span>',
                    '</div>'
                ].join('');
            }
            tooltipEl.html(innerHtml);
            tooltipEl.css({
                opacity: 1,
                left: tooltip.chart.canvas.offsetLeft + tooltip.x + 'px',
                top: tooltip.chart.canvas.offsetTop + tooltip.y + 'px',
                fontFamily: tooltip.fontFamily,
                fontSize: tooltip.fontSize,
                fontStyle: tooltip.fontStyle,
            });
        };
        var randomScalingFactor = function() {
            return Math.round(Math.random() * 100);
        };
        var lineChartData = {
            labels: ["1900-1920", "1921-1940", "1941-1960", "1961-1980", "1981-2000", "2001-2015"],
            datasets: [
             {
                 label: "My Second dataset",
                 fillColor: "rgba(151,187,205,0.2)",
                 strokeColor: "rgba(151,187,205,1)",
                 pointColor: "rgba(151,187,205,1)",
                 pointStrokeColor: "#fff",
                 pointHighlightFill: "#fff",
                 pointHighlightStroke: "rgba(151,187,205,1)",
                 data: [@ViewBag.g1,@ViewBag.g2, @ViewBag.g3, @ViewBag.g4, @ViewBag.g5, @ViewBag.g6]
             }
            ]
        };
        var ctx3 = document.getElementById("chart2").getContext("2d");
        window.myLine = new Chart(ctx3).Line(lineChartData, {
            responsive: true
        });
    </script>


</body>

</html>

BookStore/Views/List/CommentDetails.cshtml
@model BookStore.Models.Comments

@{
    ViewBag.Title = "CommentDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="listTitle">Details</div>

<br />
<table id="CommentList" style="width:100%">
    <tr>
        <td class="bookTitle">@Html.DisplayFor(model => model.BookList.Title)</td>
        <td class="title">@Html.DisplayFor(model => model.CommentTitle) / @Html.DisplayFor(model => model.Writer)</td>
        <td class="detailsList">
            <center>
                @if (User.Identity.Name.Equals("Admin@gmail.com"))
                { @Html.ActionLink("Edit", "Edit", new { id = Model.CommentsID })}
            </center>
        </td>
    </tr>
    <tr>
        <td><center><img src="@Html.DisplayFor(model => model.BookList.Picture)" style="width :100px" alt=" picture" /></center></td>
        <td class="content">@Html.DisplayFor(model => model.Content)</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td class="content"></td>
        <td class="price"></td>
    </tr>
    <tr>
        <td></td>
        <td class="content">
            <b>Rating:</b> @{
                if (Model.Rating < 1) { Console.WriteLine("No rating"); }
                else
                {
                    for (int i = 0; i < Model.Rating; i++)
                    {
                        <img src="~/Content/images/yellowstar.png" style="width :25px" alt=" picture" />
                    }
                }
            } , <b>Email:</b> @Html.DisplayFor(model => model.Email) , <b>Phone:</b> @Html.Raw("+972 ") @Html.DisplayFor(model => model.Phone)
        </td>
    </tr>
</table>
<div class="back"><center>
@Html.ActionLink("Back to Book's Details", "Details", new { id = Model.ListID })
    </center></div>
 


BookStore/Views/List/Create.cshtml
@model BookStore.Models.List

@Styles.Render("~/Content/style.css")
@Scripts.Render("~/bundles/modernizr")
<div id="addTitle">
    Add-Book
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Publisher, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Publisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Publisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" }):
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="editBack">
    @Html.ActionLink("Back to List", "Index")
</div>

BookStore/Views/List/Delete.cshtml
@model BookStore.Models.List

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>List</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookStore/Views/List/Details.cshtml
@model BookStore.Models.List

<table id="CommentList" style="width:100%">
    <tr>
        <td><center>@Html.DisplayFor(model => model.Year)</center></td>
        <td class="bookTitle">@Html.DisplayFor(model => model.Title) / @Html.DisplayFor(model => model.Author)</td>
        <td class="detailsList">
            <center>
                @if (User.Identity.Name.Equals("Admin@gmail.com"))
                { @Html.ActionLink("Edit", "Edit", new { id = Model.ListID })}
            </center>
        </td>
    </tr>
    <tr>
        <td><center><img src="@Html.DisplayFor(model => model.Picture)" style="width :100px" alt=" picture" /></center></td>
        <td class="content">@Html.DisplayFor(model => model.Content)</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td class="content"></td>
        <td class="price"></td>
    </tr>
    <tr>
        <td>@Html.DisplayFor(model => model.Price)</td>
        <td class="content">
            <b>Rating:</b> @{
                if (Model.Rating < 1) { Console.WriteLine("No rating"); }
                else
                {
                    for (int i = 0; i < Model.Rating; i++)
                    {
                        <img src="~/Content/images/yellowstar.png" style="width :25px" alt=" picture" />
                    }
                }
            } , <b>Publisher:</b> @Html.DisplayFor(model => model.Publisher) , <b>Genre:</b> @Html.DisplayFor(model => model.Genre)
        </td>
    </tr>
</table>

<h3><b>@Html.DisplayFor(model => model.Comments.Count) Comments:</b></h3>
@foreach (var item1 in Model.Comments)
{
<table id="homecom">
    <tr>
        <th>@Html.DisplayName("Writer")</th>
        <th>@Html.DisplayName("Title")</th>
        <th>@Html.DisplayName("Content")</th>
        <th>@Html.DisplayName("Rating")</th>
    </tr>
    <tr>
        <td>@Html.DisplayFor(modelItem => item1.Writer)</td>
        <td>@Html.DisplayFor(modelItem => item1.CommentTitle)</td>
        <td>@Html.DisplayFor(modelItem => item1.Content)</td>
        <td>
            @{
            if (item1.Rating < 1) { Console.WriteLine("No rating"); }
            else
            {
                for (int i = 0; i < item1.Rating; i++)
                {
                    <img src="~/Content/images/yellowstar.png" style="width :25px" alt=" picture" />
                }
            }
        }
    </td>
    <td class="details">@Html.ActionLink("Details", "CommentDetails", new { id = item1.CommentsID })</td>
</tr>
</table>
        }

BookStore/Views/List/Search.cshtml
@model IEnumerable<BookStore.Models.List>

<div class="listTitle">Search - Results</div>
        @foreach (var item in Model)
        {
            <br />
            <table id="bookList" style="width:100%">
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Year)</td>
                    <td class="title">@Html.DisplayFor(modelItem => item.Title) / @Html.DisplayFor(modelItem => item.Author)</td>
                    <td class="detailsList">
                        <center>
                            @Html.ActionLink("Details", "Details", new { id = item.ListID }) @if (User.Identity.Name.Equals("Admin@gmail.com"))
                            {@Html.Raw(" / ") @Html.ActionLink("Edit", "Edit", new { id = item.ListID })}
                        </center>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td class="content"><p>@Html.DisplayFor(modelItem => item.Content)</p></td>
                    <td><img src="@Html.DisplayFor(modelItem => item.Picture)" style="width :100px" alt=" picture" /></td>
                </tr>
                <tr>
                    <td></td>
                    <td class="publisher">@Html.DisplayFor(modelItem => item.Publisher) / @Html.DisplayFor(modelItem => item.Genre)</td>
                    <td class="price">@Html.DisplayFor(modelItem => item.Price)</td>
                </tr>
            </table>
        }
    <br />
    <center><div class="back">@Html.ActionLink("Search Again", "SearchBook", "List")</div></center>


BookStore/Views/List/SearchBook.cshtml
@model IEnumerable<BookStore.Models.List>

<h2>Search</h2>

@using (Html.BeginForm("Search", "List", FormMethod.Get))
{
    <p>
        Title: @Html.TextBox("searchString")<br />
        Author: @Html.TextBox("bookAuthor")<br />
        Price: @Html.TextBox("bookPrice")<br />
        Genre: @Html.DropDownList("bookGenre", "All")<br />
        Year: @Html.DropDownList("bookYear", "All")<br />
        <input type="submit" value="Search" />
    </p>
}